name: Code Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  codeFormat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .
